### PR TITLE
Added blink command

### PR DESCRIPTION
**Pull request by perfaram**
Pretty self-explanatory.
- Just `echo -n "blink" | nc -4u -w0 localhost 1738`, after setting the colour you wanted.
- Calling it again stops blinking.
- Changing colour while blinking changes the colour, but continues blinking.
- Blinks once per second.

That's all !

### CODE REVIEW

**Comment by perfaram** [comment]
Forgot to say that it doesn't change CPU charge. At least not enough to notice it through xCode's debugger.

**Comment by okertanov** [comment]
it breaks _imageName property usage. it might be better to introduce shadow copy of that property or just toggle image inside the timer callback w/o touching the name itself. 

i mean that blinking code may work on the ui layer, not touching external api _imageName property.
so lets say that 'blink' command just starts/stops periodic timer, and thats it, everything else is supposed to be stateless.

**Comment by perfaram** [comment]
I'll take a look at it tomorrow !

**Comment by perfaram** [comment]
What do you mean by shadow copy ?

**Comment by okertanov** [comment]
something like _blinkImageName which can store actual _imageName when altering to 'white'. but i think better is to use something like (pseudocode):
bar.image = (bar.image != currentImagePreloadedNSImage ? currentImagePreloadedNSImage : whitePreloadedNSImage);

**Comment by perfaram** [comment]
Aside this, just a small question. Why are you instantiating a new FileManager every time you call `-(NSImage*)tryImage:(NSString *)path` ? You could instantiate it once for all, isn't it ?

**Comment by okertanov** [comment]
true, that's historically. Nikita (original author & main contributor) wants to keep codebase as simple as possible.

**Comment by okertanov** [comment]
so basically as you can see there's no optimization at all. and it's ok :)

**Comment by perfaram** [comment]
Ok, but... I don't understand _why_ you would leave something that easy to optimise unoptimised. Why ?

**Pull request closed without merging**
