### PR TITLE
Added support for a custom label in the menu

### PR DESCRIPTION
**Pull request by andrewsjg**
I found it useful to identify what a particular dot was doing using a label in the menu.

I added some code to add a label to the menu based on the environment variable ANYBAR_LABEL. If this variable is set the text is shown in the menu.

### CODE REVIEW

**Comment by andrewsjg** [comment]
I see this is similar to another update using tooltips. Feel free to choose the other if it is a better solution!

**Comment by expipiplus1** [comment]
Is it possible to get one of these two PRs merged?

**Comment by expipiplus1** [comment]
Thanks!

**Comment by tonsky** [comment]
You are welcome. Published as 0.2.0

And thanks @andrewsjg for the effort, I ended up with my own slight adjustments.

**Pull request closed without merging**
